[package]
name = "data-accumulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "*"
clap = { version = "3.1.8", features = ["derive"] }

actix-web = "*"
actix-rt = "*"
actix-multipart = "0.4.0"

serde_json = "1.0"
serde = { version = "1.0.101", features = ["derive"] }

csv = "1.1"

tonic = "0.7"
prost = "0.10"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "rt"] }

influxdb = { version = "0.5.2", features = ["derive"] }
chrono = "0.4"

async-trait = "*"

diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"

[build-dependencies]
tonic-build = "0.7"


