[package]
name = "data-accumulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "*"
actix-rt = "*"
actix-multipart = "0.4.0"

serde_json = "1.0"
serde = { version = "1.0.101", features = ["derive"] }

csv = "1.1"
#dotenv = "0.11"


