[package]
name = "data-accumulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "*"
clap = { version = "3.1.8", features = ["derive"] }

actix-rt = "2.7"
serde_json = "1.0"
serde = { version = "1.0.101", features = ["derive"] }

csv = "1.1"

tonic = "0.7"
prost = "0.10"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "rt"] }

influxdb = { version = "0.5.2", features = ["derive"] }
chrono = "0.4"

async-trait = "*"

dotenv = "0.15.0"

#uuid = {version="1.1", features=["serde", "v4"]}
uuid = { version = "=0.8.1", features = ["serde", "v4"] }
diesel = { version = "=1.4.4", features = ["postgres", "r2d2", "uuidv07", "chrono"] }
#diesel = { version = "1.4", features = ["postgres", "chrono", "r2d2", "uuid", "uuidv07" ]}
actix = "0.7.9"
actix-web = "0.7.19"
actix-diesel = { version = "*", features = [ "actix-web" ] }
pretty_env_logger = "0.3.0"
failure = "0.1.5"
#actix-web-async-await = "0.2.0"
futures = "0.1"

[build-dependencies]
tonic-build = "0.7"


